version: 2
updates:
- package-ecosystem: npm
  directory: "/."
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@azure/storage-blob"
    versions:
    - "> 10.5.0"
  - dependency-name: less-loader
    versions:
    - ">= 6.a, < 7"
  - dependency-name: react-query
    versions:
    - 3.13.10
    - 3.13.7
    - 3.15.0
    - 3.9.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.0
  - dependency-name: react-dnd
    versions:
    - 12.0.0
    - 13.0.0
    - 13.0.1
    - 13.1.0
    - 14.0.0
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: aws-sdk
    versions:
    - 2.889.0
    - 2.890.0
    - 2.893.0
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@types/aws-lambda"
    versions:
    - 8.10.74
