export enum CustomEnv {
	CASSANDRA_HOST = 'DATABASE_HOST',
	CASSANDRA_KEYSPACE = 'CASSANDRA_KEYSPACE',
	CASSANDRA_PASSWORD = 'CASSANDRA_PASSWORD',
	CASSANDRA_USER = 'CASSANDRA_USER',

	REST_PORT = 'REST_PORT'
}