version: "3.8"
services:
    postgres:
        image: postgres:12
        restart: unless-stopped
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTRGRES_DATABASE: musicshare
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    backend:
        image: docker.pkg.github.com/yss14/musicshare/backend:11493a2
        restart: unless-stopped
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            NODE_ENV: production
            JWT_SECRET: somesecret
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTRGRES_DATABASE: musicshare
            FILE_STORAGE_PROVIDER: azureblob
            AZURE_STORAGE_CONNECTION_STRING: "<yourconnectionstring>"
            FRONTEND_BASEURL: http://localhost:3000
            REST_PORT: 4000
            SETUP_USERNAME: musicshare
            SETUP_PASSWORD: musicshare
            SETUP_EMAIL: donotreply@musicshare.rocks
            SETUP_SHARE_NAME: MyShare
        ports:
            - 4000:4000

    frontend:
        image: docker.pkg.github.com/yss14/musicshare/frontend:11493a2
        restart: unless-stopped
        depends_on:
            - backend
        environment:
            REACT_APP_MUSICSHARE_BACKEND_URL: http://localhost:4000
        ports:
            - 3000:80
