name: CD Staging Release

on:
    workflow_run:
        workflows: ["CI Build"]
        branches: [master]
        types:
            - completed
    workflow_dispatch:
        inputs:
            reason:
                description: Reason
                required: false

jobs:
    release_backend:
        name: Release Backend
        runs-on: ubuntu-latest

        steps:
            - uses: AutoModality/action-clean@v1
            - uses: actions/checkout@v2
            - name: Declare Git Commit Variable
              id: vars
              shell: bash
              run: |
                  echo "::set-output name=commit_hash::$GITHUB_SHA"
            - name: Download Artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: ci.build.yaml
                  commit: ${{ steps.vars.outputs.commit_hash }}
                  name: musicshare_backend
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  registry: docker.io
                  username: musicshare
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Login to GitHub Packages
              uses: docker/login-action@v1
              with:
                  registry: docker.pkg.github.com
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Docker Images
              run: |
                  GIT_COMMIT_HASH=$(git rev-parse --short HEAD)

                  docker build -f ./projects/backend/Dockerfile --rm -t docker.pkg.github.com/yss14/musicshare/backend:staging -t musicshare/backend:staging -t docker.pkg.github.com/yss14/musicshare/backend:$GIT_COMMIT_HASH -t musicshare/backend:$GIT_COMMIT_HASH - < musicshare_backend.tar

                  docker push musicshare/backend:staging
                  docker push musicshare/backend:$GIT_COMMIT_HASH

                  docker push docker.pkg.github.com/yss14/musicshare/backend:staging
                  docker push docker.pkg.github.com/yss14/musicshare/backend:$GIT_COMMIT_HASH

    release_frontend:
        name: Release Frontend
        runs-on: ubuntu-latest

        steps:
            - uses: AutoModality/action-clean@v1
            - uses: actions/checkout@v2
            - name: Declare Git Commit Variable
              id: vars
              shell: bash
              run: |
                  echo "::set-output name=commit_hash::$GITHUB_SHA"
            - name: Download Artifact
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: ci.build.yaml
                  commit: ${{ steps.vars.outputs.commit_hash }}
                  name: musicshare_frontend
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  registry: docker.io
                  username: musicshare
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Login to GitHub Packages
              uses: docker/login-action@v1
              with:
                  registry: docker.pkg.github.com
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and Push Docker Images
              run: |
                  set -e
                  set -x

                  GIT_COMMIT_HASH=$(git rev-parse --short HEAD)

                  echo $GIT_COMMIT_HASH

                  docker build -f ./projects/frontend/Dockerfile --rm -t docker.pkg.github.com/yss14/musicshare/frontend:staging -t musicshare/frontend:staging -t docker.pkg.github.com/yss14/musicshare/frontend:$GIT_COMMIT_HASH -t musicshare/frontend:$GIT_COMMIT_HASH - < musicshare_frontend.tar

                  docker push docker.pkg.github.com/yss14/musicshare/frontend:staging
                  docker push musicshare/frontend:staging

                  docker push docker.pkg.github.com/yss14/musicshare/frontend:$GIT_COMMIT_HASH
                  docker push musicshare/frontend:$GIT_COMMIT_HASH
