name: CI Build

on:
    push:
        branches: [master, chore/reduce_docker_image_size]
    pull_request:
        branches: [master]

jobs:
    build_backend:
        name: Build Backend
        runs-on: ubuntu-18.04

        services:
            postgres:
                image: postgres:9
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            minio:
                image: bitnami/minio:latest
                ports:
                    - 9000:9000
                env:
                    MINIO_ACCESS_KEY: musicshare
                    MINIO_SECRET_KEY: musicshare
            azurite:
                image: mcr.microsoft.com/azure-storage/azurite
                ports:
                    - 10000:10000

        env:
            NODE_ENV: test
            JWT_SECRET: github_actions
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            S3_HOST: "http://127.0.0.1:9000"
            S3_ACCESS_KEY: musicshare
            S3_SECRET_KEY: musicshare
            AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

        steps:
            - uses: fkirc/skip-duplicate-actions@master
              with:
                  github_token: ${{ github.token }}
            - uses: AutoModality/action-clean@v1
            - uses: actions/checkout@v2
            - name: Use Node.js 15
              uses: actions/setup-node@v1
              with:
                  node-version: 15
            - name: Run Build
              run: |
                  set -x
                  set -e

                  launch_as() {
                    local cmd_name=$1
                    shift
                    (time $@ || echo $cmd_name >> fail.txt) 2>&1 > $cmd_name.txt
                  }

                  npm ci --no-audit
                  npm run bootstrap
                  npm run build:shared-types

                  #launch_as lint npm run lint &
                  launch_as build_backend npm run build:backend &
                  #launch_as verify_backend npm run verify:backend &
                  #launch_as test_backend npm run test:ci &

                  wait
                  #cat lint.txt
                  cat build_backend.txt
                  #cat verify_backend.txt
                  #cat test_backend.txt

                  if [ -f fail.txt ]; then
                    cat fail.txt
                    exit 1
                  fi

                  tar -cf musicshare_backend.tar -C . projects/backend/build projects/backend/Dockerfile projects/react-graphql-client projects/shared-types
            - uses: actions/upload-artifact@v2
              with:
                  name: musicshare_backend
                  path: musicshare_backend.tar

    build_frontend:
        name: Build Frontend
        runs-on: ubuntu-18.04

        env:
            SKIP_PREFLIGHT_CHECK: true

        steps:
            - uses: fkirc/skip-duplicate-actions@master
              with:
                  github_token: ${{ github.token }}
            - uses: AutoModality/action-clean@v1
            - uses: actions/checkout@v2
            - name: Use Node.js 15
              uses: actions/setup-node@v1
              with:
                  node-version: 15
            - name: Run Build
              run: |
                  set -x
                  set -e

                  launch_as() {
                    local cmd_name=$1
                    shift
                    (time $@ || echo $cmd_name >> fail.txt) 2>&1 > $cmd_name.txt
                  }

                  npm ci
                  npm run bootstrap
                  npm run build:shared-types
                  npm run build:graphql-client

                  launch_as build_frontend npm run build:frontend &
                  #launch_as verify_frontend npm run verify:frontend &

                  wait
                  cat build_frontend.txt
                  #cat verify_frontend.txt

                  if [ -f fail.txt ]; then
                    cat fail.txt
                    exit 1
                  fi

                  tar -cf musicshare_frontend.tar -C . projects/frontend/build projects/frontend/Dockerfile projects/frontend/env.sh projects/frontend/config
            - uses: actions/upload-artifact@v2
              with:
                  name: musicshare_frontend
                  path: musicshare_frontend.tar

    release_backend:
        name: Release Backend
        runs-on: ubuntu-latest
        needs: build_backend

        steps:
            - uses: AutoModality/action-clean@v1
            - uses: actions/checkout@v2
            - name: Declare Git Commit Variable
              id: vars
              shell: bash
              run: |
                  echo "::set-output name=commit_hash::$GITHUB_SHA"
            - name: Download Artifact
              uses: actions/download-artifact@v2
              with:
                  name: musicshare_backend
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  registry: docker.io
                  username: musicshare
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Login to GitHub Packages
              uses: docker/login-action@v1
              with:
                  registry: docker.pkg.github.com
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Docker Images
              run: |
                  GIT_COMMIT_HASH=$(git rev-parse --short HEAD)

                  tar -xf musicshare_backend.tar -C .

                  docker build -f ./projects/backend/Dockerfile --rm -t docker.pkg.github.com/yss14/musicshare/backend:staging -t musicshare/backend:staging -t docker.pkg.github.com/yss14/musicshare/backend:$GIT_COMMIT_HASH -t musicshare/backend:$GIT_COMMIT_HASH .

                  docker push musicshare/backend:staging
                  docker push musicshare/backend:$GIT_COMMIT_HASH

                  docker push docker.pkg.github.com/yss14/musicshare/backend:staging
                  docker push docker.pkg.github.com/yss14/musicshare/backend:$GIT_COMMIT_HASH

    release_frontend:
        name: Release Frontend
        runs-on: ubuntu-latest
        needs: build_frontend

        steps:
            - uses: AutoModality/action-clean@v1
            - uses: actions/checkout@v2
            - name: Declare Git Commit Variable
              id: vars
              shell: bash
              run: |
                  echo "::set-output name=commit_hash::$GITHUB_SHA"
            - name: Download Artifact
              uses: actions/download-artifact@v2
              with:
                  name: musicshare_frontend
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  registry: docker.io
                  username: musicshare
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Login to GitHub Packages
              uses: docker/login-action@v1
              with:
                  registry: docker.pkg.github.com
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and Push Docker Images
              run: |
                  set -e
                  set -x

                  GIT_COMMIT_HASH=$(git rev-parse --short HEAD)

                  echo $GIT_COMMIT_HASH

                  tar -xf musicshare_frontend.tar -C .

                  docker build -f ./projects/frontend/Dockerfile --rm -t docker.pkg.github.com/yss14/musicshare/frontend:staging -t musicshare/frontend:staging -t docker.pkg.github.com/yss14/musicshare/frontend:$GIT_COMMIT_HASH -t musicshare/frontend:$GIT_COMMIT_HASH .

                  docker push docker.pkg.github.com/yss14/musicshare/frontend:staging
                  docker push musicshare/frontend:staging

                  docker push docker.pkg.github.com/yss14/musicshare/frontend:$GIT_COMMIT_HASH
                  docker push musicshare/frontend:$GIT_COMMIT_HASH
